### ISSUE TITLE
About GET /linodes API

### ISSUE THREAD

**Issue by hyliker** [linode/developers#108]
Hi, 
Now I have 3 linodes, I get my access_token with right scopes (linodes:view), but when I request the follow API, I got valid response, but linodes is empty.  I also generate  the Personal access tokens to test this API,  and the result is same. 

GET /linodes
curl -H "Authorization: token $TOKEN" \
    https://api.alpha.linode.com/v4/linodes

below is invalid token to request API
```
?  ~ curl -H "Authorization: token xxxxinvarlidtokenxxxx” \
>     https://api.alpha.linode.com/v4/linodes
{"reason": "Invalid OAuth token", "error": true}% 
```

below is valid token to request API, with right scopes: linodes:view 
```
?  ~ curl -H "Authorization: token xxxxvalidtokenxxxxwx” \
>     https://api.alpha.linode.com/v4/linodes
{"total_pages": 1, "total_results": 0, "page": 1, "linodes": []}%
```

**Comment by eatonphil** [comment]
Do you have three Linodes in the alpha environment or three Linodes created in the current manager (manager.linode.com)?

**Comment by hyliker** [comment]
@eatonphil I have three Linodes in the current manager(manager.linode.com).  I don't know where's alpha environment manager.  but I can login into https://login.alpha.linode.com/,  which include 2 links: 1,  Manage API clients, 2. Manage personal access tokens, but don't see any alpha linodes.

**Comment by eatonphil** [comment]
The environments are completely separate. You cannot access Linode created in manager.linode.com from the alpha API.

**Comment by SirCmpwn** [comment]
@hyliker there's not presently an alpha manager, unless you [run it yourself](https://github.com/Linode/manager). The alpha environment is *not* connected to production - it's an entirely seperate sandbox. You can create linodes through the alpha API to play with.

**Comment by eatonphil** [comment]
@hyliker if you are still confused feel free to jump on to [#linode-next](https://webchat.oftc.net/?nick=&channels=%23linode-next&uio=d4) on oftc and we can clarify.

**Comment by hyliker** [comment]
@eatonphil Thanks for your explanation. 👍

**Comment by eatonphil** [comment]
Here are a couple of links that you might find useful while you play around with the alpha environment:

* [API reference](https://developers.linode.com/reference/)
* [Alpha manager (for local testing)](https://github.com/linode/manager)
* [Engineering blog (we post updates here fairly frequently)](https://engineering.linode.com/)

Thanks for giving our alpha environment a shot!

**Comment by LiveMNCcom** [comment]
Thanks for your links. Because this is very useful for my website.
[http://livemnc.com/](url)
