### ISSUE TITLE
oauth response 500

### ISSUE THREAD

**Issue by jumkey** [linode/developers#181]
I use [linode/manager](https://github.com/linode/manager) redirect to
https://login.alpha.linode.com/oauth/authorize?client_id=5325dac9f3531409d13d&scopes=*&redirect_uri=http%3A%2F%2Flocalhost%3A3000/oauth/callback?return=%2Flinodes

When i click Continue button server response 500 `{"errors": [{"reason": "Internal server error"}]}`
I do not know what this is going on
Did i use the wrong way?

**Comment by eatonphil** [comment]
Hey! Looks like this is an issue on our end. We are investigating it.

**Comment by eatonphil** [comment]
I believe we identified and fixed the problem, could you give this another try to confirm it is working now?

**Comment by jumkey** [comment]
Yes

**Comment by eatonphil** [comment]
Great! Please let us know if you encounter any other issues.
