### ISSUE TITLE
Mockup for updated docs

### ISSUE THREAD

**Issue by eatonphil** [linode/developers#191]
<img width="726" alt="screen shot 2017-04-11 at 4 44 10 pm" src="https://cloud.githubusercontent.com/assets/3925912/24930037/1fb0c424-1ed6-11e7-982b-d58345c81b83.png">
<img width="729" alt="screen shot 2017-04-11 at 4 44 16 pm" src="https://cloud.githubusercontent.com/assets/3925912/24930038/1fb22882-1ed6-11e7-8169-4f28d50fa1a2.png">

**Comment by mparke** [comment]
Items/considerations based on in-person:

- Needs filters (in nav?) + examples
- Need params (in nav?) + examples
- Needs enumerated fields example 
- Response section needs full body example - tabbed between table and json example
- Section for status codes and error formats
- Denote which endpoints are operations that involve cost
- Denote which endpoints are filterable ( and if possible, which filters do and do not apply - last time I checked there may be special cases )
- Consideration for collapsed sidebar
- Consideration for collapsed sections, e.g. GET/POST
- Consideration for changelog displayed in the docs
- Consideration for copy to clipboard for appopriate pre/code instances
- Less harsh on the black/white contrast? Sync up manager color scheme
- Consider sidebar nested list items ( 1 level deep ) for categories, for exaple: Linodes > Instances, which would promote shorter/easier to read endpoint urls in the index itself

```
  Linodes
      Instances
```

- Consider field types as subtitles of the response field, leaving the right side of a table for a description of the field, for example:

```
  Field              Description
      linodes          A list of linodes
      *Array*  
```

**Comment by mparke** [comment]
@abemassry @na3d Anything else missing you guys can think of ?

**Comment by mparke** [comment]
Follow ups:

- https://github.com/linode/developers/issues/185
- https://github.com/linode/developers/issues/186
- https://github.com/linode/developers/issues/187
- https://github.com/linode/developers/issues/192
- https://github.com/linode/developers/issues/193
- https://github.com/linode/developers/issues/194

**Comment by eatonphil** [comment]
Closing this for follow-ups.
