### ISSUE TITLE
Mockup filters

### ISSUE THREAD

**Issue by mparke** [linode/developers#192]

**Comment by eatonphil** [comment]
On the endpoint page:

![screen shot 2017-04-18 at 4 31 01 pm](https://cloud.githubusercontent.com/assets/3925912/25151698/7f0a4732-2454-11e7-962b-98dcb7535244.png)

And on the Filtering page itself:

![screen shot 2017-04-18 at 4 30 44 pm](https://cloud.githubusercontent.com/assets/3925912/25151697/7f057428-2454-11e7-95e7-541e6d7c2abc.png)

**Comment by eatonphil** [comment]
Closing out for this iteration
