### ISSUE TITLE
Mockup status codes / error fields

### ISSUE THREAD

**Issue by mparke** [linode/developers#194]

**Comment by eatonphil** [comment]
On the endpoint page:

![screen shot 2017-04-18 at 4 31 01 pm](https://cloud.githubusercontent.com/assets/3925912/25151698/7f0a4732-2454-11e7-962b-98dcb7535244.png)

And on the Filtering page itself:

![screen shot 2017-04-18 at 4 30 44 pm](https://cloud.githubusercontent.com/assets/3925912/25151697/7f057428-2454-11e7-95e7-541e6d7c2abc.png)

**Comment by eatonphil** [comment]
![screen shot 2017-04-18 at 4 44 28 pm](https://cloud.githubusercontent.com/assets/3925912/25152232/53fd378c-2456-11e7-8d77-5ed69244d8f9.png)

**Comment by eatonphil** [comment]
Closing out for this iteration
