### ISSUE TITLE
No images API in v4?

### ISSUE THREAD

**Issue by pathbreak** [linode/developers#201]
Just a question...
I'm not finding the v4 equivalent of the old Images API: [https://www.linode.com/api/image](https://www.linode.com/api/image)
Is this feature no longer available? I didn't find it in the new Linode Manager either.

To give some background, I'm looking for a way in v4 to create a disk which can be cloned while creating new Linodes. The old image API supported it. It made creation of clusters of nodes with exact same software and OS updates very simple, and it was much faster than cloning the entire Linode.

**Comment by eatonphil** [comment]
Support for images is on our radar but, as you've noticed, is not currently supported.

An aside: this repo is old and no longer used. I'm going to delete this repo in a few minutes after you've had a chance to read my response. If you'd like, you can create more issues on our primary repo: https://github.com/linode/manager/.

**Comment by pathbreak** [comment]
Thank you for that info, and sorry about raising in the wrong repo.
