### ISSUE TITLE
OAuth Refresh Token

### ISSUE THREAD

**Issue by dmyers** [linode/developers#202]
Is there a way to refresh a token? Without this tokens expires and can't be used with many automation workflows or services one of which I am building.

The docs also don't reference an `expires_at` field which is included (recent change)? https://developers.linode.com/v4/access

**Comment by eatonphil** [comment]
Hey! To answer your question, we're in the middle of some changes to the oauth server to bring some naming and such in line with the spec. Adding the ability to refresh a token is also on the roadmap.

Anyway, this repo is pretty old and no longer the point of reference for the manager or for the API docs. I mean to close it down one of these days... You can make future issues at github.com/linode/manager.

**Comment by dmyers** [comment]
Oh okay that sounds good thanks!
