### ISSUE TITLE
yaml changes not picked up on guard server

### ISSUE THREAD

**Issue by yoshizzle** [linode/developers#28]
@RobertDeRose - when running `bundle exec guard`, changes made in yaml files aren't picked up, and while the page does live-reload, the changes are not present.  Not sure where in the line this is breaking, but running the server as `jekyll server --watch` does the right thing (minus the swanky live reload jawn).

*This is typed by Josh for reals*

**Comment by jamesottinger** [comment]
The guard stuff was removed in 7ffae38 and several others that followed it, which resolves this issue. Thanks @yoshizzle! Closing.
