### ISSUE TITLE
Link to documentation on account page is wrong.

### ISSUE THREAD

**Issue by anoland** [linode/developers#55]
On https://login.alpha.linode.com/apps the link to OAuth documentation is wrong. It links to http://linode.sircmpwn.com/reference/#authentication

**Comment by SirCmpwn** [comment]
Whoops! Thought we got all of those.

**Comment by SirCmpwn** [comment]
Fixed! Looks like we did catch it, but there was an issue deploying the latest login packages. It's all good :smile:
