### ISSUE TITLE
Use 429 status code instead of 420

### ISSUE THREAD

**Issue by mjmasn** [linode/developers#66]
I notice you're using the slightly jokey "420 Enhance Your Calm" for rate limiting. Without wanting to be a party pooper you should probably be using "429 Too Many Requests" for that seeing as it's actually part of an RFC (albeit only a proposal at this stage). See http://tools.ietf.org/html/rfc6585#section-4

Note that newer versions of the Twitter API have replaced 420 with 429 (https://dev.twitter.com/overview/api/response-codes).

**Comment by SirCmpwn** [comment]
Doesn't actually matter what the number is so long as it's documented and consistent.

**Comment by mjmasn** [comment]
Well yes, you can send a 200 or a 418 if you really want but it's not great for interoperability. To give a real world example: lots of sites (usually javascript based apps) are sending a 200 when they really mean 404 and that really messes with Google results. You end up with pages like http://example.org/a/dde/hf/some/nonsense being indexed with the content of the homepage or a soft-404 page.

In this case it's probably not a problem for 99% of use cases, but somebody always gets burnt by stuff like this in a way nobody ever thought of. Better to fix things in alpha than in production...

**Comment by SirCmpwn** [comment]
Well, you could argue that the 2xx/3xx/4xx/5xx categories are important, but beyond that it's not really that important for things that are loosely standardized.

**Comment by SirCmpwn** [comment]
Closing due to lack of outside interest in the discussion and no compelling reason to change.
