### ISSUE TITLE
Documentation: dnszones:modify PUT has the wrong docs

### ISSUE THREAD

**Issue by anoland** [linode/developers#80]
On https://developers.linode.com/reference/#ep-dnszones-methods under the PUT description it has some lines that describe a new system, not a new zone.

**Comment by anoland** [comment]
Same under https://developers.linode.com/reference/#ep-dnszones-id-records-id-methods too.

**Comment by displague** [comment]
Thanks for pointing this out.  The yaml files are fine.  This appears to be a problem in the doc generator.
