### ISSUE TITLE
Update guides with new labels and other breaking changes

### ISSUE THREAD

**Issue by eatonphil** [linode/developers#97]
The following have parts that need to be updated now that ids have changed:

* https://developers.linode.com/guides/python-guide/
* https://developers.linode.com/libraries/python-reference/
* https://developers.linode.com/guides/create-a-linode/
* https://developers.linode.com/guides/curl-guide/

**Comment by jamesottinger** [comment]
It looks like we got them all. Closing. Thanks @eatonphil!
